name: retail_data_pipeline
version: "1.0.0"
config-version: 2

profile: retail_data_pipeline

model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]

flags:
  send_anonymous_usage_stats: false

models:
  retail_data_pipeline:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
